eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka/
  instance:
    #
    # 生产环境下不建议修改以下两项，更改Eureka更新频率将会打破服务器的自我保护功能
    #
    # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 10
    # 续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 30
server:
  port: 8760
spring:
  application:
    name: service-client